spring:
  application:
    name: Attribute-Service
  config:
    activate:
      on-profile: prod
  cache:
    type: redis
    cache-names: redis-cache
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5435/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5435/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 900MB

redisson:
  host: localhost
  port: 6379

url:
  productService: http://localhost:7070

server:
  port: 4040

otel:
  service:
    name: "attribute-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"

resilience4j:
  ratelimiter:
    instances:
      attributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
      productTypeAttributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s
      productAttributeLimiter:
        limit-for-period: 30
        limit-refresh-period: 1s